-- Create testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,       -- Author/Client Name
  role text,                  -- e.g. CEO
  company text,               -- e.g. Google
  content text not null,      -- The testimonial quote
  image text,                 -- URL to author image
  metric text,                -- e.g. "2.4x"
  metric_label text,          -- e.g. "Growth"
  color text default 'blue',  -- Accent color (blue, emerald, purple)
  featured boolean default false
);

-- Enable Row Level Security
alter table public.testimonials enable row level security;

-- Create policies (DROP first to avoid conflicts on re-run)
drop policy if exists "Enable read access for all users" on public.testimonials;
create policy "Enable read access for all users" on public.testimonials
  for select using (true);

drop policy if exists "Enable insert for authenticated users only" on public.testimonials;
create policy "Enable insert for authenticated users only" on public.testimonials
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Enable update for authenticated users only" on public.testimonials;
create policy "Enable update for authenticated users only" on public.testimonials
  for update using (auth.role() = 'authenticated');

drop policy if exists "Enable delete for authenticated users only" on public.testimonials;
create policy "Enable delete for authenticated users only" on public.testimonials
  for delete using (auth.role() = 'authenticated');

-- STORAGE POLICIES
-- 1. Create the generic 'images' bucket if it doesn't exist
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- 2. Allow public access to view images
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'images' );

-- 3. Allow authenticated users to upload images
drop policy if exists "Authenticated Upload" on storage.objects;
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- 4. Allow authenticated users to update/delete their images
drop policy if exists "Authenticated Update" on storage.objects;
create policy "Authenticated Update"
on storage.objects for update
using ( bucket_id = 'images' and auth.role() = 'authenticated' );

drop policy if exists "Authenticated Delete" on storage.objects;
create policy "Authenticated Delete"
on storage.objects for delete
using ( bucket_id = 'images' and auth.role() = 'authenticated' );
