-- Create testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,       -- Author/Client Name
  role text,                  -- e.g. CEO
  company text,               -- e.g. Google
  content text not null,      -- The testimonial quote
  image text,                 -- URL to author image
  metric text,                -- e.g. "2.4x"
  metric_label text,          -- e.g. "Growth"
  color text default 'blue',  -- Accent color (blue, emerald, purple)
  featured boolean default false
);

-- Enable Row Level Security
alter table public.testimonials enable row level security;

-- Create policies
-- Allow everyone to read testimonials (Public API)
create policy "Enable read access for all users" on public.testimonials
  for select using (true);

-- Allow admins to insert/update/delete (Authenticated users only for now, refine if needed)
-- Assuming authenticated users are admins based on email check in API route, 
-- but consistent RLS is good too.
create policy "Enable insert for authenticated users only" on public.testimonials
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.testimonials
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.testimonials
  for delete using (auth.role() = 'authenticated');
